// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rcdxilillaqqycpkoomj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJjZHhpbGlsbGFxcXljcGtvb21qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDI3NDgsImV4cCI6MjA3NDYxODc0OH0.ZMRIqN0gyjJ4ejyfF9xCEwa66zS7nRRZl1THFQ95j-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});